name: Build Artifact

on:
  push:
  pull_request:
    branches: [ "master" ]


env:
  OWNER_IN_LOWER: shuishiyuanzhong
  ARTIFACT_NAME_LINUX: h5s-record-amd64
  ARTIFACT_NAME_WINDOWS: h5s-record-windows.exe
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  ACTOR: ${{ github.actor }}

jobs:
  build-and-push-wordpress-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build linux amd64 artifact
        run: make amd

      - name: Build windows artifact
        run: make windows

      - name: Install Oras-0.13.0
        run: |
          curl -LO https://github.com/oras-project/oras/releases/download/v0.13.0/oras_0.13.0_linux_amd64.tar.gz
          mkdir -p oras-install/
          tar -zxf oras_0.13.0_*.tar.gz -C oras-install/
          mv oras-install/oras /usr/local/bin/
          rm -rf oras_0.13.0_*.tar.gz oras-install/
          oras version
          
      - name: SetUp ARTIFACT VERSION
        run: |
          echo "ARTIFACT_VERSION=$(echo ${{ github.ref_name}} | tr '[:upper:]' '[:lower:]')" > ${GITHUB_ENV}

      - name: Publish to GitHub Packages
        run: |
          cd bin
          echo ${{ secrets.GITHUB_TOKEN }} | oras login ghcr.io -u ${ACTOR} --password-stdin
          oras push ghcr.io/${OWNER_IN_LOWER}/${ARTIFACT_NAME_LINUX}:${ARTIFACT_VERSION} ${ARTIFACT_NAME_LINUX}
          oras push ghcr.io/${OWNER_IN_LOWER}/${ARTIFACT_NAME_WIN}:${ARTIFACT_VERSION} ${ARTIFACT_NAME_WIN}




