name: Docker Image CI

on:
  push:
    branches-ignore: ['P3042_backend']
  workflow_dispatch:
    inputs:
      release_tag:
        required: false
        type: string

env:
  GITHUB_REGISTRY: ghcr.io
  HARBOR_REGISTRY: img.luex.xyz/dev
  IMAGE_NAME: ones-cn-cms
  NODE_BUILD: production
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  SMS_CONFIG: dev
  HARBOR_IMAGE_PATH: img.luex.xyz/dev/h5s-record
  GITHUB_IMAGE_PATH: ghcr.io/${{ github.repository }}

jobs:
  build-and-push-wordpress-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to Harbor
        uses: docker/login-action@v2.0.0
        with:
          registry: ${{ env.HARBOR_REGISTRY }}
          username: admin
          password: Gu000803


      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: |
            ${{ env.HARBOR_IMAGE_PATH }}
          tags: ${{ inputs.release_tag }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: devops/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

